openapi: 3.0.0
info:
  title: "Trails Management API"
  description: "API for managing trails, features, location points, and user authentication."
  version: "1.1.2"
servers:
  - url: "http://127.0.0.1:8000/api"

paths:
  /login:
    post:
      summary: "Authenticate user and generate JWT token"
      operationId: "routes.login"
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: "User's email address"
                password:
                  type: string
                  description: "User's password"
      responses:
        "200":
          description: "Login successful"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  token:
                    type: string
                  role:
                    type: string
                    description: "User's role (Administrator or Standard)"
        "401":
          description: "Unauthorized"
        "500":
          description: "Authentication service unavailable"

  /trails/admin:
    get:
      summary: "Retrieve all trails (Administrator view)"
      operationId: "routes.admin_trails"
      tags:
        - Trails
      security:
        - BearerAuth: []
      responses:
        "200":
          description: "List of trails for administrators"
          content:
            application/json:
              schema:
                type: object
                properties:
                  trails:
                    type: array
                    items:
                      $ref: "#/components/schemas/Trail"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"

  /trails/standard:
    get:
      summary: "Retrieve all trails (Standard view)"
      operationId: "routes.standard_trails"
      tags:
        - Trails
      security:
        - BearerAuth: []
      responses:
        "200":
          description: "List of trails for standard users"
          content:
            application/json:
              schema:
                type: object
                properties:
                  trails:
                    type: array
                    items:
                      $ref: "#/components/schemas/Trail"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"

  /trails/admin/{trail_id}:
    get:
      summary: "Retrieve a single trail by ID (Administrator view)"
      operationId: "routes.trail_by_id_admin"
      tags:
        - Trails
      parameters:
        - $ref: "#/components/parameters/trail_id"
      security:
        - BearerAuth: []
      responses:
        "200":
          description: "Trail details for administrators"
          content:
            application/json:
              schema:
                type: object
                properties:
                  trail:
                    $ref: "#/components/schemas/Trail"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "Trail not found"

  /trails/{trail_id}/features:
    post:
      summary: "Add features to a trail"
      operationId: "routes.add_trail_features"
      tags:
        - Features
      parameters:
        - $ref: "#/components/parameters/trail_id"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
                description: "Feature name to add to the trail"
      security:
        - BearerAuth: []
      responses:
        "200":
          description: "Features added successfully"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "400":
          description: "Failed to add features"
        "401":
          description: "Unauthorized"

  /trails/{trail_id}/features/{feature_id}:
    delete:
      summary: "Remove a feature from a trail"
      operationId: "routes.remove_trail_feature"
      tags:
        - Features
      parameters:
        - $ref: "#/components/parameters/trail_id"
        - $ref: "#/components/parameters/feature_id"
      security:
        - BearerAuth: []
      responses:
        "200":
          description: "Feature removed successfully"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "400":
          description: "Failed to remove feature"
        "401":
          description: "Unauthorized"

  /trails/{trail_id}/location-points:
    put:
      summary: "Update location points for a trail"
      operationId: "routes.edit_location_points"
      tags:
        - Location Points
      parameters:
        - $ref: "#/components/parameters/trail_id"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/LocationPoint"
      security:
        - BearerAuth: []
      responses:
        "200":
          description: "Location points updated successfully"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "400":
          description: "Failed to update location points"
        "401":
          description: "Unauthorized"

  /trails/{trail_id}/location-points/{location_point_id}:
    delete:
      summary: "Remove a location point from a trail"
      operationId: "routes.delete_location_point"
      tags:
        - Location Points
      parameters:
        - $ref: "#/components/parameters/trail_id"
        - $ref: "#/components/parameters/location_point_id"
      security:
        - BearerAuth: []
      responses:
        "200":
          description: "Location point removed successfully"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "400":
          description: "Failed to remove location point"
        "401":
          description: "Unauthorized"

components:
  schemas:
    Trail:
      type: object
      properties:
        TrailID:
          type: integer
          description: "ID of the trail"
        Trail_name:
          type: string
          description: "Name of the trail"
        Trail_Summary:
          type: string
          description: "Summary of the trail"
        Trail_Description:
          type: string
          description: "Detailed description of the trail"
        Difficulty:
          type: string
          description: "Difficulty level of the trail"
        Location:
          type: string
          description: "Location of the trail"
        Length:
          type: number
          description: "Length of the trail in kilometers"
        Elevation_gain:
          type: integer
          description: "Elevation gain of the trail in meters"
        Route_type:
          type: string
          description: "Type of route (e.g., Loop, Out & Back)"
    TrailCreate:
      type: object
      required:
        - Trail_name
        - Location
        - Length
        - Difficulty
        - Route_type
      properties:
        Trail_name:
          type: string
        Trail_Summary:
          type: string
        Trail_Description:
          type: string
        Difficulty:
          type: string
        Location:
          type: string
        Length:
          type: number
        Elevation_gain:
          type: integer
        Route_type:
          type: string
    Feature:
      type: string
      description: "Feature name"
    LocationPoint:
      type: object
      properties:
        LocationPointID:
          type: integer
          description: "ID of the location point"
        Latitude:
          type: number
          description: "Latitude of the location point"
        Longitude:
          type: number
          description: "Longitude of the location point"
        Description:
          type: string
          description: "Description of the location point"

  parameters:
    trail_id:
      name: "trail_id"
      in: path
      description: "ID of the trail"
      required: true
      schema:
        type: integer
    feature_id:
      name: "feature_id"
      in: path
      description: "ID of the feature"
      required: true
      schema:
        type: integer
    location_point_id:
      name: "location_point_id"
      in: path
      description: "ID of the location point"
      required: true
      schema:
        type: integer

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      x-bearerInfoFunc: config.bearer_info_func

